name: image_form_field_x
description: Upload images in Flutter forms
version: 0.0.5
homepage: https://github.com/tshedor/flutter_image_form_field
author: Tim Shedor <opensource@timshedor.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.1+10
